name: Docker CI

on:
  push:
    branches: [ master ]
    tags:
      - v*
  pull_request:
    branches: [ master ]

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    # Running this job only for master branch
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2

    - name: Build docker image
      run: make docker/build

    - name: Tag docker image
      run: make docker/tag TAG_NAME=latest

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Push the Docker image
      run: make docker/push
